version: "3"
services:
#  app:
#    build: .
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/hospital
#      - SPRING_DATASOURCE_USERNAME=hospital
#      - SPRING_DATASOURCE_PASSWORD=hospital
#    depends_on:
#      - postgres
  postgres:
    build: database
    environment:
      - POSTGRES_USER=hospital
      - POSTGRES_PASSWORD=hospital
    volumes:
      - postgresdata:/var/lib/postgresql/data
    ports:
      - "54321:5432"
volumes:
  postgresdata:
